Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 160

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
